Repository pass-culture/pass-culture-app-native, pull requests merged in 2025-05, with the labels that each got.

#8095 (PC-35990) refactor(ci): remove unecessary yarn and java in workflow
  .github/workflows/dev_on_workflow_call_e2e_android.yml
  .github/workflows/dev_on_workflow_call_e2e_ios.yml
Labels: e2e Android

#8084 (PC-35123) feat(useGTLPlaylist): querify hooks
  __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
  package.json
  src/features/gtlPlaylist/api/fetchGTLPlaylistConfig.native.test.ts
  src/features/gtlPlaylist/fixtures/contentfulGtlPlaylistSnap.ts
  src/features/gtlPlaylist/fixtures/gtlPlaylistRequestSnap.ts
  src/features/gtlPlaylist/gtlPlaylistHelpers.test.ts
  src/features/gtlPlaylist/gtlPlaylistHelpers.ts
  src/features/gtlPlaylist/hooks/useGTLPlaylists.ts
  src/features/gtlPlaylist/queries/useGTLPlaylistsQuery.native.test.ts
  src/features/gtlPlaylist/queries/useGTLPlaylistsQuery.ts
  src/features/gtlPlaylist/queries/useGetFormattedAndFilteredOffersByGtl.test.ts
  src/features/gtlPlaylist/queries/useGetFormattedAndFilteredOffersByGtl.ts
  src/features/gtlPlaylist/queries/useGetGTLPlaylistConfigByLabelQuery.test.ts
  src/features/gtlPlaylist/queries/useGetGTLPlaylistConfigByLabelQuery.ts
  src/features/gtlPlaylist/queries/useGetGTLPlaylistConfigQuery.test.ts
  src/features/gtlPlaylist/queries/useGetGTLPlaylistsConfigQuery.ts
  src/features/gtlPlaylist/queries/useGetOffersByGtlQuery.ts
  src/features/gtlPlaylist/types.ts
  src/features/home/api/useGetOffersData.ts
  src/features/home/types.ts
  src/features/search/pages/ThematicSearch/Book/BookPlaylists.native.test.tsx
  src/features/search/pages/ThematicSearch/Book/BookPlaylists.tsx
  src/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx
  src/features/search/pages/ThematicSearch/ThematicSearch.web.test.tsx
  src/features/venue/components/VenueBody/VenueBody.native.test.tsx
  src/features/venue/components/VenueContent/VenueContent.native.test.tsx
  src/features/venue/pages/Venue/Venue.native.test.tsx
  src/features/venue/pages/Venue/Venue.perf.test.tsx
  src/features/venue/pages/Venue/Venue.tsx
  src/features/venue/pages/Venue/Venue.web.test.tsx
  src/libs/algolia/fetchAlgolia/fetchMultipleOffers/fetchMultipleOffers.test.ts
  src/libs/algolia/fetchAlgolia/fetchMultipleOffers/fetchMultipleOffers.ts
  src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/useAdaptOffersPlaylistParameters.ts
  src/libs/algolia/fetchAlgolia/fetchOffersByGTL.native.test.ts
  src/libs/algolia/fetchAlgolia/fetchOffersByGTL.ts
  src/libs/algolia/types.ts
  src/libs/queryKeys.ts
Labels: e2e iOS

#8099 (PC-36021) refactor(e2e): Replace conditional date logic with dynamic JS for D+3
  .github/workflows/dev_on_workflow_call_e2e_ios.yml
  .maestro/tests/subFolder/auth/LoginFromProfileForBeneficiaryUser.yml
  .maestro/tests/subFolder/commons/getCurrentDay.js
  .maestro/tests/subFolder/search/SearchBookableCinemaOffer.yml
  .maestro/tests/subFolder/search/SearchBookableDuoOffer.yml
  .maestro/tests/subFolder/search/SearchOfferFromText.yml
  .maestro/tests/subFolder/tutorial/onboarding/Onboard16AndLocalization.yml
  .maestro/tests/subFolder/tutorial/onboarding/Onboard18.yml
Labels: e2e

#8128 (PC-36126) fix(e2e): update ios localization screen wording
  .maestro/tests/subFolder/tutorial/onboarding/Onboard16AndLocalization.yml
  .maestro/tests/subFolder/tutorial/onboarding/Onboard18.yml
Labels: e2e iOS

#8131 (BSR) fix(e2e): use only days instead of full date
  .maestro/tests/subFolder/booking/BookCinemaOffer.yml
  .maestro/tests/subFolder/booking/BookDuoOffer.yml
  .maestro/tests/subFolder/booking/DaySelectionCinema.yml
  .maestro/tests/subFolder/commons/getCurrentDay.js
  .maestro/tests/subFolder/search/SearchBookableCinemaOffer.yml
  .maestro/tests/subFolder/search/SearchBookableDuoOffer.yml
Labels: e2e Android

#8146 (PC-36090) feat(inputs): no placeholder when input has format
  .maestro/README.md
  .maestro/tests/subFolder/auth/AgeStepInfoLoss.yml
  .maestro/tests/subFolder/auth/LoginAndReactivation.yml
  .maestro/tests/subFolder/auth/LoginFromFavorites.yml
  .maestro/tests/subFolder/auth/LoginFromModal.yml
  .maestro/tests/subFolder/auth/LoginFromProfileAfterSignup.yml
  .maestro/tests/subFolder/auth/LoginFromProfileForBeneficiaryUser.yml
  .maestro/tests/subFolder/auth/LoginWithWrongEmail.yml
  .maestro/tests/subFolder/auth/LoginWithWrongPassword.yml
  .maestro/tests/subFolder/auth/PasswordStepInfoLoss.yml
  .maestro/tests/subFolder/auth/SignupFromProfile.yml
  __snapshots__/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.native.test.tsx.native-snap
  __snapshots__/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.native.test.tsx.native-snap
  __snapshots__/features/auth/pages/login/Login.native.test.tsx.native-snap
  __snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/profile/SetAddress.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/profile/SetCity.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/ChangeCity/ChangeCity.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/ChangeCity/ChangeCity.web.test.tsx.web-snap
  __snapshots__/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/NewEmailSelection/NewEmailSelection.native.test.tsx.native-snap
  doc/development/how-to/react-hook-form.md
  src/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.native.test.tsx
  src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.tsx
  src/features/auth/pages/login/Login.native.test.tsx
  src/features/auth/pages/signup/SetEmail/SetEmail.native.test.tsx
  src/features/auth/pages/signup/SignupForm.native.test.tsx
  src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.tsx
  src/features/identityCheck/pages/profile/SetAddress.native.test.tsx
  src/features/identityCheck/pages/profile/SetAddress.tsx
  src/features/identityCheck/pages/profile/SetAddress.web.test.tsx
  src/features/identityCheck/pages/profile/SetCity.native.test.tsx
  src/features/profile/components/CitySearchInput/CitySearchInput.native.test.tsx
  src/features/profile/components/CitySearchInput/CitySearchInput.tsx
  src/features/profile/pages/ChangeCity/ChangeCity.native.test.tsx
  src/features/profile/pages/ChangeEmail/ChangeEmailContent.tsx
  src/features/profile/pages/NewEmailSelection/NewEmailSelection.native.test.tsx
  src/features/profile/pages/NewEmailSelection/NewEmailSelection.tsx
  src/shared/forms/controllers/EmailInputController.native.test.tsx
  src/ui/components/inputs/EmailInput/EmailInput.tsx
Labels: e2e

#8169 (PC-36254) fix(e2e): make date iso on cloud runs and fix offer selection
  .maestro/tests/subFolder/booking/BookPhysicalOffer.yml
  .maestro/tests/subFolder/commons/getCurrentDay.js
Labels: e2e
