Repository pass-culture/pass-culture-app-native, pull requests merged in 2025-07, with the labels that each got.

#8357 (PC-34673) fix(e2e): remove useless case and add scroll for favorite ios flow
  .maestro/tests/SignupJourney.yml
  .maestro/tests/subFolder/favorite/AddToFavorite.yml
Labels: e2e

#8370 chore(deps): upgrade react-native-permissions
  ios/PassCulture.xcodeproj/project.pbxproj
  ios/PassCulture/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: e2e

#8400 (PC-36961) fix(app): use isInitialLoading instead of isLoading
  src/cheatcodes/queries/useCheatcodesFeatureFlagQuery.ts
  src/features/auth/context/SettingsContext.tsx
  src/features/favorites/hooks/useFavorite.ts
  src/features/forceUpdate/helpers/useMinimalBuildNumber.ts
  src/features/search/pages/ThematicSearch/api/useThematicSearchPlaylists.ts
  src/libs/firebase/firestore/featureFlags/useFeatureFlagOptions.ts
  src/libs/react-query/usePersistQuery.ts
Labels: e2e

#8465 (PC-37198) feat(e2e): handle appsFlyer trackers in E2E proxy
  src/libs/campaign/campaignTracker.ts
Labels: e2e Android

#8443 (PC-37006) feat(perfs): add slack notif and labeled run for performance test
  .github/workflows/dev_on_pull_request_run_e2e.yml
  .github/workflows/dev_on_schedule_flashlight_android.yml
Labels: e2e perfs
