Repository pass-culture/pass-culture-app-native, pull requests merged in 2025-02, with the labels that each got.

#7634 (PC-34024) feat(tutorial): add FAQ banner and link in ProfileTutorial…
  .env.integration
  .env.perf
  .env.production
  .env.staging
  .env.testing
  __snapshots__/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformationCreditV3.native.test.tsx.native-snap
  src/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformationCreditV3.native.test.tsx
  src/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformationCreditV3.tsx
  src/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformationCreditV3.web.test.tsx
  src/libs/analytics/__mocks__/logEventAnalytics.ts
  src/libs/analytics/logEventAnalytics.ts
  src/libs/environment/fixtures.ts
  src/libs/environment/schema.ts
  src/libs/firebase/analytics/events.ts
  whiteListEnv.js
Labels: preview

#7703 (BSR) docs(adr): first stone for decision records and more notation (writing culture)
  doc/decision-records/DR000 - template.md
  doc/decision-records/DR001 - writing adr.md
  doc/development/how-to/debugging.md
Labels: documentation, enhancement

#7726 (PC-34662) feat(Notifications): create notifications modal
  __snapshots__/features/offer/components/FavoriteAuthModal/FavoriteAuthModal.native.test.tsx.native-snap
  __snapshots__/features/offer/components/NotificationAuthModal/NotificationAuthModal.native.test.tsx.native-snap
  src/features/auth/api/useSignIn.ts
  src/features/navigation/RootNavigator/types.ts
  src/features/offer/components/FavoriteAuthModal/FavoriteAuthModal.native.test.tsx
  src/features/offer/components/FavoriteAuthModal/FavoriteAuthModal.tsx
  src/features/offer/components/NotificationAuthModal/NotificationAuthModal.native.test.tsx
  src/features/offer/components/NotificationAuthModal/NotificationAuthModal.tsx
  src/features/offer/components/OfferFooter/OfferFooter.native.test.tsx
  src/features/offer/components/OfferFooter/StickyFooterContent.tsx
  src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.native.test.tsx
  src/ui/components/buttons/FavoriteButton.tsx
Labels: Waiting for review, Squad conversion

#7751 (PC-34806) fix(e2e): handle PassForAll activation on Android run
  .maestro/tests/subFolder/auth/LogoutFromProfile.yml
  .maestro/tests/subFolder/auth/SignupFromProfile.yml
  .maestro/tests/subFolder/tutorial/onboarding/Onboard16AndLocalization.yml
  .maestro/tests/subFolder/tutorial/onboarding/Onboard18.yml
Labels: preview

#7759 (PC-34662) feat(ComingSoon): fix auth modal
  __snapshots__/features/offer/components/FavoriteAuthModal/FavoriteAuthModal.native.test.tsx.native-snap
  src/features/offer/components/FavoriteAuthModal/FavoriteAuthModal.tsx
  src/features/offer/components/OfferFooter/StickyFooterContent.tsx
Labels: Waiting for review, Squad conversion
