Repository pass-culture/pass-culture-app-native, pull requests merged in 2025-10, with the labels that each got.

#8740 (PC-38205) feat(a11y): add new heading in AccessibilityDeclaration
  __snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap
  __snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/Accessibility/AccessibilityDeclarationMobileAndroid.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/Accessibility/AccessibilityDeclarationMobileIOS.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/Accessibility/AccessibilityDeclarationWeb.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/TutorialAgeInformationCredit/ProfileTutorialAgeInformationCredit.native.test.tsx.native-snap
  __snapshots__/features/search/pages/SearchLanding/SearchLanding.native.test.tsx.native-snap
  __snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
  __snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
  __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
  doc/decision-records/DR009 - accessibility-audit.md
  src/features/profile/pages/Accessibility/AccessibilityDeclarationMobileBase.tsx
  src/features/profile/pages/Accessibility/AccessibilityDeclarationWeb.tsx
  src/features/search/components/NumberOfResults/NumberOfResults.tsx
  src/features/search/components/SearchTitleAndWidget/SearchTitleAndWidget.tsx
  src/features/subscription/components/ThematicSubscriptionBlock.tsx
  src/features/venue/components/PracticalInformation/PracticalInformation.tsx
  src/ui/components/headers/ContentHeader.tsx
Labels: a11y

#8752 (PC-38131) feat(bonification): create screens in cheatcodes
  src/cheatcodes/pages/CheatcodesMenu.tsx
  src/cheatcodes/pages/features/bonification/CheatcodesNavigationBonification.tsx
  src/features/bonification/pages/BonificationBirthDate.native.test.tsx
  src/features/bonification/pages/BonificationBirthDate.tsx
  src/features/bonification/pages/BonificationBirthPlace.native.test.tsx
  src/features/bonification/pages/BonificationBirthPlace.tsx
  src/features/bonification/pages/BonificationError.native.test.tsx
  src/features/bonification/pages/BonificationError.tsx
  src/features/bonification/pages/BonificationIntroduction.native.test.tsx
  src/features/bonification/pages/BonificationIntroduction.tsx
  src/features/bonification/pages/BonificationNames.native.test.tsx
  src/features/bonification/pages/BonificationNames.tsx
  src/features/bonification/pages/BonificationRecap.native.test.tsx
  src/features/bonification/pages/BonificationRecap.tsx
  src/features/bonification/pages/BonificationTitle.native.test.tsx
  src/features/bonification/pages/BonificationTitle.tsx
  src/features/bonification/schemas/BonificationBirthPlaceSchema.ts
  src/features/bonification/schemas/BonificationNamesSchema.ts
  src/features/navigation/CheatcodesStackNavigator/CheatcodesStackNavigator.tsx
  src/features/navigation/CheatcodesStackNavigator/CheatcodesStackTypes.ts
  src/features/navigation/CheatcodesStackNavigator/cheatcodesStackNavigatorPathConfig.tsx
  src/features/navigation/RootNavigator/linking/rootStackNavigatorPathConfig.ts
  src/features/navigation/SubscriptionStackNavigator/SubscriptionStackNavigator.tsx
  src/features/navigation/SubscriptionStackNavigator/SubscriptionStackTypes.ts
Labels: preview

#8754 (BSR) fix(e2e): update checkbox required label
  .maestro/tests/subFolder/auth/LoginGoogleFromProfil.yml
  .maestro/tests/subFolder/auth/SignupFromProfile.yml
  .maestro/tests/subFolder/booking/BookCinemaOffer.yml
  .maestro/tests/subFolder/booking/BookDuoOffer.yml
  .maestro/tests/subFolder/booking/BookMusicalOffer.yml
  .maestro/tests/subFolder/booking/BookPhysicalOffer.yml
  .maestro/tests/subFolder/commons/GoToBookingFromVenue.yml
Labels: e2e
