Repository pass-culture/pass-culture-app-native, pull requests merged in 2025-04, with the labels that each got.

#7941 (PC-35246) refactor(app): clean venue.publicName || venue.name because it is managed by backend
  src/features/bookOffer/components/BookingDetails.native.test.tsx
  src/features/bookOffer/components/BookingDetails.tsx
  src/features/bookings/helpers/getLocationLabel.test.ts
  src/features/bookings/helpers/getLocationLabel.ts
  src/features/offer/components/OfferPlace/OfferPlace.tsx
  src/features/offer/components/OfferVenueBlock/useVenueBlock.ts
  src/features/offer/components/OfferVenueButton/OfferVenueButton.native.test.tsx
  src/features/offer/components/OfferVenueButton/OfferVenueButton.tsx
  src/features/share/helpers/getShareOffer.tsx
  src/features/share/helpers/getShareVenue.ts
  src/features/venue/components/VenueContent/VenueContent.tsx
  src/features/venue/components/VenueHeader/VenueHeader.native.test.tsx
  src/features/venue/components/VenueHeader/VenueHeader.tsx
  src/features/venue/helpers/useVenueSearchParameters.ts
  src/libs/address/__mocks__/useFormatFullAddress.ts
  src/libs/location/components/WhereSection.tsx
  src/queries/searchVenuesOffer/useSearchVenueOffersInfiniteQuery.ts
  src/shared/address/addressFormatter.test.ts
  src/shared/address/addressFormatter.ts
  src/shared/offer/helpers/getOfferLocationName.test.ts
  src/shared/offer/helpers/getOfferLocationName.ts
Labels: preview

#7980 (PC-35479) fix(home): infinite render loop fix add stale time to useRemoteConfigQuery
  src/libs/firebase/remoteConfig/queries/useRemoteConfigQuery.ts
Labels: e2e

#7973 (PC-35523) fix(e2e): update deletion scenario, avoid hidekeyboard flakiness
  .maestro/tests/AccessSignupFromBlock.yml
  .maestro/tests/subFolder/home/OpenActivationModuleFromHome.yml
  .maestro/tests/subFolder/profil/DeletionReactivation.yml
  .maestro/tests/subFolder/profil/LegalInfoSection.yml
  .maestro/tests/subFolder/venue/VerifyVenueMap.yml
Labels: e2e iOS

#7990 (PC-35578) fix(e2e): bypass localization poppin in home
  .maestro/tests/subFolder/booking/BookMusicalOffer.yml
  .maestro/tests/subFolder/home/OpenActivationModuleFromHome.yml
Labels: e2e iOS

#7904 (PC-34760) refactor(profile): queries
  src/features/auth/pages/signup/AccountCreated/AccountCreated.native.test.tsx
  src/features/birthdayNotifications/pages/RecreditBirthdayNotification.native.test.tsx
  src/features/birthdayNotifications/pages/RecreditBirthdayNotification.tsx
  src/features/bookings/pages/BookingDetails/BookingDetails.web.test.tsx
  src/features/cookies/components/CookiesSettings.native.test.tsx
  src/features/cookies/pages/CookiesDetails.native.test.tsx
  src/features/cookies/pages/CookiesDetails.web.test.tsx
  src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.tsx
  src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.tsx
  src/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx
  src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.native.test.tsx
  src/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx
  src/features/profile/components/Header/ProfileHeader/ProfileHeader.web.test.tsx
  src/features/profile/pages/ChangeCity/ChangeCity.tsx
  src/features/profile/pages/ChangeStatus/useSubmitChangeStatus.tsx
  src/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.tsx
  src/features/profile/pages/FeedbackInApp/FeedbackInApp.tsx
  src/features/profile/pages/NotificationSettings/NotificationsSettings.tsx
  src/features/profile/queries/useAnonymizeAccountMutation.ts
  src/features/profile/queries/useFeedbackMutation.ts
  src/features/profile/types.ts
  src/features/search/components/sections/Category/Category.native.test.tsx
  src/features/search/components/sections/Price/Price.native.test.tsx
  src/features/subscription/helpers/useThematicSubscription.tsx
  src/features/subscription/page/OnboardingSubscription.tsx
  src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistParameters.native.test.ts
  src/libs/utm/getUtmParamsConsent.native.test.ts
  src/queries/profile/usePatchProfileMutation.ts
  src/queries/profile/useResetRecreditAmountToShowMutation.ts
Labels: archi

#8020 (PC-35696) feat(a11y): unlock portrait mode
  __mocks__/react-native-orientation-locker.ts
  __snapshots__/features/profile/pages/DisplayPreference/DisplayPreference.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
  __snapshots__/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx.native-snap
  __snapshots__/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx.native-snap
  __snapshots__/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx.native-snap
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/passculture/MainActivity.kt
  ios/PassCulture/AppDelegate.mm
  ios/PassCulture/Info.plist
  ios/Podfile.lock
  jest.config.js
  jest/jest.setup.ts
  package.json
  src/App.tsx
  src/features/navigation/ProfileStackNavigator/ProfileStack.ts
  src/features/navigation/ProfileStackNavigator/ProfileStackNavigator.tsx
  src/features/navigation/ProfileStackNavigator/profileRoutes.ts
  src/features/profile/pages/DisplayPreference/DisplayPreference.native.test.tsx
  src/features/profile/pages/DisplayPreference/DisplayPreference.tsx
  src/features/profile/pages/DisplayPreference/DisplayPreference.web.test.tsx
  src/features/profile/pages/Profile.native.test.tsx
  src/features/profile/pages/Profile.tsx
  src/features/profile/pages/Profile.web.test.tsx
  src/features/search/components/FilterSwitchWithLabel/FilterSwitchWithLabel.tsx
  src/libs/analytics/__mocks__/logEventAnalytics.ts
  src/libs/analytics/logEventAnalytics.ts
  src/libs/firebase/analytics/events.ts
  src/shared/hook/useOrientationLocked.native.test.ts
  src/shared/hook/useOrientationLocked.ts
  yarn.lock
Labels: preview

#8030 (PC-35498) feat(e2e): add modular test tags for functional scopes
  .github/workflows/dev_on_pull_request_run_e2e.yml
  .github/workflows/dev_on_workflow_call_e2e_android.yml
  .github/workflows/dev_on_workflow_call_e2e_ios.yml
  .maestro/README.md
  .maestro/tests/AccessSignupFromBlock.yml
  .maestro/tests/FavoriteSectionCheck.yml
  .maestro/tests/FirstLaunch.yml
  .maestro/tests/ProfileAndDeletionSectionCheck.yml
  .maestro/tests/SearchAndBookCinemaOffer.yml
  .maestro/tests/SearchAndBookDuoOffer.yml
  .maestro/tests/SearchAndBookOffers.yml
  .maestro/tests/SearchJourney.yml
  .maestro/tests/SignupAndActivation.yml
  .maestro/tests/UserNotConnectedMode.yml
  .maestro/tests/VenueMapCheck.yml
  scripts/run_e2e_tests.sh
Labels: e2e:squad-decouverte

#8040 (PC-35781) chore(lib): RN 74
  Gemfile
  Gemfile.lock
  __snapshots__/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformationCredit.native.test.tsx.native-snap
  __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  ios/PassCulture.xcodeproj/project.pbxproj
  ios/PassCulture/AppDelegate.mm
  ios/PassCulture/Info.plist
  ios/Podfile.lock
  metro.config.js
  package.json
  yarn.lock
Labels: e2e
