Repository pass-culture/pass-culture-app-native, pull requests merged in 2025-03, with the labels that each got.

#7778 (PC-34682) feat(firestore): dissociate RemoteGenericBanner and Remote…
  __snapshots__/features/home/pages/Home.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/DisableActivation.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/Profile.web.test.tsx.web-snap
  src/cheatcodes/pages/CheatcodesMenu.tsx
  src/cheatcodes/pages/features/remoteBanner/CheatcodesScreenRemoteBanner.tsx
  src/cheatcodes/pages/features/remoteBanners/CheatcodesScreenRemoteBanners.tsx
  src/features/home/components/banners/SignupBanner.native.test.tsx
  src/features/home/components/banners/SignupBanner.tsx
  src/features/home/components/modules/banners/HomeBanner.native.test.tsx
  src/features/home/components/modules/banners/HomeBanner.tsx
  src/features/home/pages/ThematicHome.native.test.tsx
  src/features/identityCheck/pages/DisableActivation.native.test.tsx
  src/features/identityCheck/pages/DisableActivation.tsx
  src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.native.test.tsx
  src/features/navigation/CheatcodesStackNavigator/CheatcodesStackNavigator.tsx
  src/features/navigation/CheatcodesStackNavigator/CheatcodesStackNavigatorConfig.tsx
  src/features/navigation/CheatcodesStackNavigator/types.ts
  src/features/offer/components/VenueSelectionListHeader/VenueSelectionListHeader.native.test.tsx
  src/features/profile/components/Badges/SubscriptionMessageBadge.tsx
  src/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx
  src/features/profile/components/Header/CreditHeader/CreditHeader.stories.tsx
  src/features/profile/components/Header/CreditHeader/CreditHeader.tsx
  src/features/profile/components/Header/HeaderWithGreyContainer/HeaderWithGreyContainer.stories.tsx
  src/features/profile/components/Header/HeaderWithGreyContainer/HeaderWithGreyContainer.tsx
  src/features/profile/components/Header/LoggedOutHeader/LoggedOutHeader.native.test.tsx
  src/features/profile/components/Header/LoggedOutHeader/LoggedOutHeader.tsx
  src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.native.test.tsx
  src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.tsx
  src/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx
  src/features/profile/components/Header/ProfileHeader/ProfileHeader.tsx
  src/features/profile/components/Header/ProfileHeader/ProfileHeader.web.test.tsx
  src/features/profile/pages/Profile.tsx
  src/features/remoteBanners/banners/RemoteActivationBanner.native.test.tsx
  src/features/remoteBanners/banners/RemoteActivationBanner.tsx
  src/features/remoteBanners/banners/RemoteGenericBanner.native.test.tsx
  src/features/remoteBanners/banners/RemoteGenericBanner.tsx
  src/features/remoteBanners/components/RemoteBanner.native.test.tsx
  src/features/remoteBanners/components/RemoteBanner.tsx
  src/features/remoteBanners/components/RemoteBanner.web.test.tsx
  src/features/remoteBanners/utils/remoteBannerSchema.ts
  src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx
  src/libs/analytics/__mocks__/logEventAnalytics.ts
  src/libs/analytics/logEventAnalytics.ts
  src/libs/firebase/analytics/events.ts
  src/libs/firebase/firestore/types.ts
  src/shared/Banners/GeolocationBanner.native.test.tsx
  src/shared/Banners/GeolocationBanner.tsx
  src/ui/components/ModuleBanner/SystemBanner.tsx
Labels: preview

#7787 (PC-3461) refactor(global): auth queries
  __snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap
  src/features/auth/api/useOAuthState.ts
  src/features/auth/api/useSignUp.ts
  src/features/auth/components/SSOButton/SSOButton.tsx
  src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.tsx
  src/features/auth/pages/login/Login.tsx
  src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx
  src/features/auth/pages/signup/SignupConfirmationEmailSent/EmailResendModal.tsx
  src/features/auth/pages/signup/SignupForm.native.test.tsx
  src/features/auth/pages/signup/SignupForm.tsx
  src/features/auth/pages/suspendedAccount/AccountStatusScreenHandler/AccountStatusScreenHandler.native.test.tsx
  src/features/auth/pages/suspendedAccount/AccountStatusScreenHandler/AccountStatusScreenHandler.tsx
  src/features/auth/pages/suspendedAccount/SuspendedAccountUponUserRequest/SuspendedAccountUponUserRequest.native.test.tsx
  src/features/auth/pages/suspendedAccount/SuspendedAccountUponUserRequest/SuspendedAccountUponUserRequest.tsx
  src/features/auth/queries/signup/useAppSignupMutation.ts
  src/features/auth/queries/signup/useGoogleSignupMutation.ts
  src/features/auth/queries/useAccountSuspendForHackSuspicionMutation.ts
  src/features/auth/queries/useAccountSuspendMutation.ts
  src/features/auth/queries/useAccountSuspensionDateQuery.native.test.ts
  src/features/auth/queries/useAccountSuspensionDateQuery.ts
  src/features/auth/queries/useAccountSuspensionStatusQuery.native.test.ts
  src/features/auth/queries/useAccountSuspensionStatusQuery.ts
  src/features/auth/queries/useAccountUnsuspendMutation.native.test.ts
  src/features/auth/queries/useAccountUnsuspendMutation.ts
  src/features/auth/queries/useChangePasswordMutation.ts
  src/features/auth/queries/useEmailValidationRemainingResendQuery.ts
  src/features/auth/queries/useOAuthStateQuery.native.test.ts
  src/features/auth/queries/useOAuthStateQuery.ts
  src/features/auth/queries/useResendEmailValidationMutation.ts
  src/features/auth/queries/useResetPasswordMutation.ts
  src/features/auth/queries/useSignInMutation.ts
  src/features/auth/queries/useValidateEmailMutation.ts
  src/features/profile/pages/ChangePassword/ChangePassword.tsx
  src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.tsx
  src/features/profile/pages/DeleteProfile/SuspendAccountConfirmationWithoutAuthentication.tsx
  src/libs/react-native-google-sso/useGoogleLogin.ts
  src/libs/react-native-google-sso/useGoogleLogin.web.ts
Labels: do not merge yet, guild archi

#7838 (PC-35138) refactor(e2e): optimize booking tests to reduce flakiness and complexity
  .maestro/tests/subFolder/booking/BookCinemaOffer.yml
  .maestro/tests/subFolder/booking/BookDuoOffer.yml
  .maestro/tests/subFolder/booking/DaySelectionCinema.yml
Labels: e2e

#7840 (PC-34992) feat(offer): reaction feature from offer header
  src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.native.test.tsx
  src/features/offer/components/OfferBody/OfferBody.tsx
  src/features/offer/components/OfferContent/OfferContent.tsx
  src/features/offer/components/OfferContent/OfferContent.web.tsx
  src/features/offer/components/OfferContent/OfferContentBase.tsx
  src/features/offer/components/OfferHeader/OfferReactionHeaderButton.native.test.tsx
  src/features/offer/components/OfferHeader/OfferReactionHeaderButton.tsx
  src/features/offer/components/OfferReactionSection/OfferReactionSection.native.test.tsx
  src/features/offer/components/OfferReactionSection/OfferReactionSection.tsx
  src/features/offer/helpers/renderOfferPageTestUtil.tsx
  src/features/offer/pages/Offer/Offer.native.test.tsx
  src/features/offer/pages/Offer/Offer.tsx
  src/features/offer/types.ts
  src/queries/bookings/useEndedBookingFromOfferIdQuery.ts
  src/queries/offer/useOfferQuery.native.test.ts
  src/queries/offer/useOfferQuery.ts
Labels: squad découverte

#7850 (PC-34987) feat(a11y): update autoComplete and textContentType in som…
  __snapshots__/features/identityCheck/pages/phoneValidation/SetPhoneNumber.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/profile/SetAddress.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/profile/SetAddress.web.test.tsx.web-snap
  __snapshots__/features/identityCheck/pages/profile/SetCity.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/profile/SetCity.web.test.tsx.web-snap
  __snapshots__/features/identityCheck/pages/profile/SetName.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/ChangeCity/ChangeCity.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/ChangeCity/ChangeCity.web.test.tsx.web-snap
  src/cheatcodes/pages/others/CheatcodesScreenNewCaledonia.tsx
  src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx
  src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.tsx
  src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.tsx
  src/features/identityCheck/pages/profile/SetAddress.tsx
  src/features/identityCheck/pages/profile/SetName.tsx
  src/features/profile/components/CitySearchInput/CitySearchInput.tsx
  src/features/search/components/PriceInputController/PriceInputController.tsx
Labels: a11y, guild a11y

#7882 (PC-35298) fix(e2e): change skip accessiblity label in Onboard18
  .maestro/tests/subFolder/tutorial/onboarding/Onboard18.yml
Labels: e2e iOS

#7887 (PC-35216) feat(a11y): use customFocusOutline in some components
  __snapshots__/features/identityCheck/pages/Stepper.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/identification/ubble/SelectIDOrigin.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/identification/ubble/SelectIDStatus.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/identification/ubble/SelectPhoneStatus.web.test.tsx.web-snap
  __snapshots__/features/profile/pages/Accessibility/Accessibility.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/DeleteProfileReason/DeleteProfileReason.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/TrackEmailChange/TrackEmailChange.native.test.tsx.native-snap
  __snapshots__/features/tutorial/pages/AgeSelectionFork.native.test.tsx.native-snap
  __snapshots__/features/tutorial/pages/EligibleUserAgeSelection.native.test.tsx.native-snap
  __snapshots__/features/tutorial/pages/onboarding/OnboardingAgeInformation.native.test.tsx.native-snap
  __snapshots__/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.native.test.tsx.native-snap
  __snapshots__/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformationCreditV3.native.test.tsx.native-snap
  scripts/noUncheckedIndexedAccess_snapshot.txt
  src/cheatcodes/pages/features/identityCheck/CheatcodesNavigationIdentityCheck.tsx
  src/cheatcodes/pages/features/profile/CheatcodesNavigationProfile.tsx
  src/features/bookOffer/pages/BookingOfferModal.native.test.tsx
  src/features/home/components/banners/SignupBanner.native.test.tsx
  src/features/home/components/modules/video/OldVideoModuleDesktop.tsx
  src/features/home/components/modules/video/OldVideoModuleMobile.tsx
  src/features/home/components/modules/video/VideoModuleDesktop.tsx
  src/features/home/components/modules/video/VideoModuleMobile.tsx
  src/features/identityCheck/pages/Stepper.web.test.tsx
  src/features/identityCheck/pages/identification/ubble/SelectIDOrigin.web.test.tsx
  src/features/identityCheck/pages/identification/ubble/SelectIDStatus.web.test.tsx
  src/features/identityCheck/pages/identification/ubble/SelectPhoneStatus.web.test.tsx
  src/features/location/components/LocationModalButton.tsx
  src/features/offer/components/OfferImageCarousel/OfferImageCarouselItem.tsx
  src/features/offer/components/VenueSelectionList/VenueSelectionList.native.test.tsx
  src/features/offer/components/VenueSelectionListHeader/VenueSelectionListHeader.native.test.tsx
  src/features/offer/components/VenueSelectionModal/VenueSelectionModal.native.test.tsx
  src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.web.test.tsx
  src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.web.test.tsx
  src/features/remoteBanners/components/RemoteBanner.native.test.tsx
  src/features/remoteBanners/components/RemoteBanner.tsx
  src/features/remoteBanners/components/RemoteBanner.web.test.tsx
  src/features/search/components/SearchList/SearchList.native.test.tsx
  src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx
  src/shared/Banners/GeolocationBanner.native.test.tsx
  src/ui/components/InternalStep/InternalStep.tsx
  src/ui/components/ModuleBanner/SystemBanner.native.test.tsx
  src/ui/components/ModuleBanner/SystemBanner.tsx
  src/ui/components/StepButton/StepButton.tsx
  src/ui/components/accessibility/AccessibleUnorderedList.tsx
  src/ui/components/buttons/HeroButtonList.tsx
  src/ui/components/buttons/buttonWithLinearGradient/ButtonWithLinearGradient.tsx
  src/ui/components/touchable/Touchable.tsx
  src/ui/components/touchableLink/TouchableLink.tsx
  src/ui/components/touchableLink/types.ts
Labels: a11y

#7863 (PC-34823) refactor(reactions): queries for /features/reactions
  src/features/bookings/pages/Bookings/Bookings.native.test.tsx
  src/features/bookings/pages/Bookings/Bookings.tsx
  src/features/bookings/pages/Bookings/Bookings.web.test.tsx
  src/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx
  src/features/bookings/pages/EndedBookings/EndedBookings.tsx
  src/features/home/components/IncomingReactionModalContainer/IncomingReactionModalContainer.native.test.tsx
  src/features/home/components/IncomingReactionModalContainer/IncomingReactionModalContainer.tsx
  src/features/navigation/helpers/useTabBarItemBadges.test.ts
  src/features/navigation/helpers/useTabBarItemBadges.ts
  src/features/offer/components/OfferReactionSection/OfferReactionSection.native.test.tsx
  src/features/offer/pages/Offer/Offer.tsx
  src/features/reactions/queries/useAvailableReactionQuery.test.ts
  src/features/reactions/queries/useAvailableReactionQuery.ts
  src/features/reactions/queries/useReactionMutation.test.ts
  src/features/reactions/queries/useReactionMutation.ts
Labels: archi

#7901 (PC-34982) feat(a11y): More precise accessibilityLabels when possible
  __snapshots__/features/identityCheck/pages/phoneValidation/SetPhoneNumber.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/profile/SetAddress.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/profile/SetAddress.web.test.tsx.web-snap
  __snapshots__/features/identityCheck/pages/profile/SetCity.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/profile/SetCity.web.test.tsx.web-snap
  __snapshots__/features/identityCheck/pages/profile/SetName.native.test.tsx.native-snap
  src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.native.test.tsx
  src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx
  src/features/identityCheck/pages/profile/SetAddress.tsx
  src/features/identityCheck/pages/profile/SetCity.tsx
  src/features/identityCheck/pages/profile/SetName.native.test.tsx
  src/features/identityCheck/pages/profile/SetName.tsx
Labels: a11y, e2e

#7919 (PC-34902) feat(HomePlaylistsTtitles): emojis should appear but not be readable by voicOver
  __snapshots__/features/home/components/modules/video/VideoModal.native.test.tsx.native-snap
  __snapshots__/features/home/pages/GenericHome.native.test.tsx.native-snap
  __snapshots__/features/home/pages/Home.native.test.tsx.native-snap
  __snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
  __snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
  __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
  scripts/noUncheckedIndexedAccess_snapshot.txt
  src/features/home/components/AccessibleTitle.native.test.tsx
  src/features/home/components/AccessibleTitle.tsx
  src/features/home/components/modules/HighlightOfferModule.tsx
  src/features/home/components/modules/HomeModule.native.test.tsx
  src/features/home/components/modules/HomeModule.web.test.tsx
  src/features/home/components/modules/categories/CategoryListModule.tsx
  src/features/home/components/modules/video/OldVideoModuleDesktop.tsx
  src/features/home/components/modules/video/OldVideoModuleMobile.tsx
  src/features/home/components/modules/video/VideoModule.native.test.tsx
  src/features/home/components/modules/video/VideoModuleDesktop.tsx
  src/features/home/components/modules/video/VideoModuleMobile.tsx
  src/features/home/components/modules/video/VideoMonoOfferTile.tsx
  src/features/home/pages/GenericHome.tsx
  src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.tsx
  src/features/venue/components/VenueOffers/VenueOffersList.tsx
  src/ui/components/PassPlaylist.tsx
Labels: a11y
