Repository pass-culture/pass-culture-app-native, pull requests merged in 2025-08, with the labels that each got.

#8531 (PC-37323) feat(accessibility): update accessibility declaration mobile
  __snapshots__/features/profile/pages/Accessibility/Accessibility.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/Accessibility/AccessibilityDeclarationMobile.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/Accessibility/AccessibilityDeclarationMobileAndroid.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/Accessibility/AccessibilityDeclarationMobileIOS.native.test.tsx.native-snap
  src/features/navigation/ProfileStackNavigator/ProfileStackNavigator.tsx
  src/features/navigation/ProfileStackNavigator/profileStackNavigatorPathConfig.ts
  src/features/navigation/RootNavigator/types.ts
  src/features/profile/pages/Accessibility/Accessibility.native.test.tsx
  src/features/profile/pages/Accessibility/Accessibility.tsx
  src/features/profile/pages/Accessibility/AccessibilityDeclarationMobile.tsx
  src/features/profile/pages/Accessibility/AccessibilityDeclarationMobileAndroid.native.test.tsx
  src/features/profile/pages/Accessibility/AccessibilityDeclarationMobileAndroid.tsx
  src/features/profile/pages/Accessibility/AccessibilityDeclarationMobileAndroid.web.test.tsx
  src/features/profile/pages/Accessibility/AccessibilityDeclarationMobileBase.tsx
  src/features/profile/pages/Accessibility/AccessibilityDeclarationMobileIOS.native.test.tsx
  src/features/profile/pages/Accessibility/AccessibilityDeclarationMobileIOS.tsx
  src/features/profile/pages/Accessibility/AccessibilityDeclarationMobileIOS.web.test.tsx
Labels: preview

#8564 (PC-37580) fix(deployment): temporary downgrade of runner to bypass error
  .github/workflows/dev_on_workflow_call_e2e_ios.yml
  .github/workflows/dev_on_workflow_environment_ios_deploy.yml
  .xcode-version
  scripts/check_xcode_version.sh
Labels: e2e iOS

#8579 (PC-37483) feat(a11y): make visible content accessible to assistive t…
  __snapshots__/features/home/pages/Home.native.test.tsx.native-snap
  __snapshots__/features/identityCheck/pages/profile/SetStatus.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/ChangeStatus/ChangeStatus.native.test.tsx.native-snap
  __snapshots__/features/profile/pages/DisplayPreference/DisplayPreference.native.test.tsx.native-snap
  src/features/home/components/banners/SignupBanner.tsx
  src/features/home/components/modules/banners/HomeBanner.tsx
  src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.tsx
  src/features/profile/pages/DisplayPreference/DisplayPreference.tsx
  src/shared/Banners/GeolocationBanner.tsx
  src/ui/components/ModuleBanner/SystemBanner.stories.tsx
  src/ui/components/ModuleBanner/SystemBanner.tsx
  src/ui/components/radioSelector/RadioSelector.tsx
  src/ui/components/radioSelector/RadioSelector.web.test.tsx
Labels: a11y
